services:
  codeclimbers-platform-server:
    image: ghcr.io/codeclimbersio/platform-server
    container_name: codeclimbers-platform-server
    ports:
      - "8000:8000"
    depends_on:
      - codeclimbers-redis
    env_file:
      - .env
    restart: always
    
  codeclimbers-redis:
    image: redis:latest
    container_name: codeclimbers-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always
volumes:
  redis_data: