name: Deploy to Production

on:
  workflow_run:
    workflows: ["Docker Image CI/CD"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh $USER@$HOST << EOF
            cd ~/projects/codeclimbers/platform-codeclimbers
            docker-compose pull codeclimbers-platform-web
            docker-compose up -d --no-deps codeclimbers-platform-web
            docker image prune -f
          EOF
